
// export const actionsEnums = {
//   UPDATE_USERPROFILE_NAME : 'UPDATE_USERPROFILE_NAME ',
//   PARSE_URL: 'PARSE_URL'
//   PARSE_URL_FULFILLED: 'PARSE_URL_FULFILLED'
// }

export enum Actions {
  UPDATE_USERPROFILE_NAME = 'UPDATE_USERPROFILE_NAME ',
  PARSE_URL = 'PARSE_URL',
  PARSE_URL_FULFILLED = 'PARSE_URL_FULFILLED'
}